# Deep Learning NanoDegree Notes


## Project 1



### Matrix Maths Refresher

1. Scalar - 0 dimensions
1. Vector - 1 dimension (row or column)
1. Matrix - 2 dimensions (rows and columns)
1. Tensor - n dimensions

Vectors can be considered matrices with 1 row or 1 column

Value location in a matrix is row,column.


#### numpy

In [3]:
import numpy as np

We can use [n-dimensional arrays](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#arrays-ndarray) in numpy to represent tensors. Every item in the array must have the same type.

In [4]:
s = np.array(5)

In [6]:
s.shape # Scalar

()

In [10]:
x = s + 3
x

8

In [11]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [12]:
v.shape

(3,)

In [14]:
x = v[1]
x

2

In [15]:
v[1:]

array([2, 3])

In [16]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
m.shape

(3, 3)

In [18]:
m[1][2]

6

In [20]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [21]:
t.shape

(3, 3, 2, 1)

In [22]:
v = np.array([1,2,3,4])
v.shape

(4,)

In [23]:
x = v.reshape(1,4)
x

array([[1, 2, 3, 4]])

In [24]:
x.shape

(1, 4)

In [25]:
x = v[None, :]
x

array([[1, 2, 3, 4]])

In [26]:
x.shape

(1, 4)

In [27]:
x = v[:, None]
x

array([[1],
       [2],
       [3],
       [4]])

In [28]:
x.shape

(4, 1)

#### Element Wise Matrix Operations

In [29]:
values = np.array([1,2,3,4,5])
values + 5

array([ 6,  7,  8,  9, 10])

In [31]:
values * 5

array([ 5, 10, 15, 20, 25])

In [32]:
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
a+b

array([[ 3,  7],
       [11, 15]])

In [37]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
print("A: " + str(a.shape))
print("C: " + str(c.shape))
try:
    a+c
except Exception as e:
    print(e)

A: (2, 2)
C: (3, 3)
operands could not be broadcast together with shapes (2,2) (3,3) 


#### Matrix Multiplication



In [39]:
a = np.array([0,2,4,6])
b = np.array([8,10,12,14])
c = np.array([1,3,5])
d = np.array([7,9,11])
e = np.array([13,15,17])
f = np.array([19,21,23])
m = np.array([a,b])
n = np.array([c,d,e,f])

In [40]:
m

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [41]:
n

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [55]:
# Get row 0
m[0,:]

array([0, 2, 4, 6])

In [54]:
# Get column 0
m[:,0]

array([0, 8])

In [59]:
print(np.dot(m[0,:],n[:,0]))
print(np.dot(m[0,:],n[:,1]))
print(np.dot(m[0,:],n[:,2]))

180
204
228


In [60]:
print(np.dot(m[1,:],n[:,0]))
print(np.dot(m[1,:],n[:,1]))
print(np.dot(m[1,:],n[:,2]))

500
588
676


In [61]:
mn = np.matmul(m,n)
mn

array([[180, 204, 228],
       [500, 588, 676]])

In [62]:
# Columns of first matrix must equal the rows of second matrix
# Resulting matrix has number of rows of first matrix and number of columns of second matrix
m.shape, n.shape, mn.shape

((2, 4), (4, 3), (2, 3))

[Dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) and [Matrix Multiplication](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) are different for n!=2 dimensions.

In [63]:
# For 2 dimensional data, np.dot and np.matmul are the same
np.dot(m,n)

array([[180, 204, 228],
       [500, 588, 676]])

#### Transposes

In [65]:
m.T

array([[ 0,  8],
       [ 2, 10],
       [ 4, 12],
       [ 6, 14]])

In [67]:
m.shape, m.T.shape

((2, 4), (4, 2))

In [66]:
n.T

array([[ 1,  7, 13, 19],
       [ 3,  9, 15, 21],
       [ 5, 11, 17, 23]])

In [68]:
n.shape, n.T.shape

((4, 3), (3, 4))

In [64]:
mn.T

array([[180, 500],
       [204, 588],
       [228, 676]])

In [69]:
mn.shape, mn.T.shape

((2, 3), (3, 2))

You can safely use a transpose in a matrix multiplication if the data in both of your original matrices is arranged as rows.

### Neural Networks

A perceptron / neuron is one node in a neural network. The perceptron takes several inputs and calculates the weighted sum of those inputs based on the weight for each input. The resulting value is then checked against an activation function. Based on the activation function, the perceptron will emit the appropriate value.

In [71]:
inputs = np.array([0.7, -0.3])
weights = np.array([0.1, 0.8])
np.dot(inputs, weights), 0.1*0.7 + 0.8*-0.3

(-0.16999999999999998, -0.16999999999999998)

`Delta_w = learning_rate * error * derivative_of_activation * input value`

`delta = error derivative_of_activation`

`w_i+1 = w_i + learning_rate * delta * input_value`